- clean: ['~']

- link:
    ~/.vimrc: .vimrc
    ~/.gitignore: .gitignore
    ~/.gitconfig: .gitconfig
    ~/.bash_profile: .bash_profile
    ~/.vim: .vim/

- shell:
    - [sudo apt-get install tree, Installing tree]
    - [mkdir -p ~/work/dev, Create work/dev dir]


