- clean: ['~']

- link:
    ~/.vimrc: vimenv/general/local.vim
    ~/.gitignore: .gitignore
    ~/.gitconfig: .gitconfig
    ~/.bash_profile: vimenv/general/local.bash
    ~/.vim: vimenv/active_environment/plugin/


- shell:
    - [mkdir -p ~/work/dev, Create work/dev dir]
    - [mkdir -p vimenv/active_environment, Create active_environment dir]
    - [vimenv -e, Activating general environment]



